spring:
  application:
    name: batch
  datasource:
    url: jdbc:mysql://localhost:3306/batch
    username: root
    password: 12345678

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


  batch:
    initialize-schema: ALWAYS

# Disable job run at start up
  batch:
    job:
      enabled: false

server:
  port: 9091


