spring:
  application:
    name: batch
  datasource:
    url: jdbc:mysql://localhost:3306/batch
    username: root
    password: 12345678

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: ALWAYS

server:
  port: 9091
